### PR TITLE
halt.php remove jobs work for both gearman and redis alike

### PR DESCRIPTION
**Pull request by kowalskiw**
Provide both network/queue managers tools in `halt.php`.

### CODE REVIEW

**Comment by kowalskiw** [comment]
I've already tested this solution - works fine.

**Comment by zarooba01** [comment]
Installed php-redis and added to installers. Halt php works fine.
It was necessery to restart redis-workers on nodes, because they didn't want to finish calculations. After restart everything worked well. To be checked if that problem will apear in the future.

**Review by zarooba01 — CHANGES_REQUESTED** [review]
As above.

**Review by zarooba01 — APPROVED** [review]
Ok

**Pull request merged**
